version: '3.5'

services:
  php:
    build: .
    container_name: mestre-dos-codigos-php
    ports:
      - 8080:80
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true
    volumes:
      - .:/var/www/html